"""User, Resume, and Post tables

Revision ID: 0f11689d9cf5
Revises: 
Create Date: 2020-09-11 12:16:04.048781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f11689d9cf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('resume',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_index(op.f('ix_resume_file_name'), 'resume', ['file_name'], unique=False)
    op.create_table('listing',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.resume_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_listing_company'), 'listing', ['company'], unique=False)
    op.create_index(op.f('ix_listing_date_added'), 'listing', ['date_added'], unique=False)
    op.create_index(op.f('ix_listing_description'), 'listing', ['description'], unique=False)
    op.create_index(op.f('ix_listing_location'), 'listing', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_location'), table_name='listing')
    op.drop_index(op.f('ix_listing_description'), table_name='listing')
    op.drop_index(op.f('ix_listing_date_added'), table_name='listing')
    op.drop_index(op.f('ix_listing_company'), table_name='listing')
    op.drop_table('listing')
    op.drop_index(op.f('ix_resume_file_name'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
