"""empty message

Revision ID: 20a9668c5fb6
Revises: 9a728cfbb15a
Create Date: 2020-09-21 14:42:14.589122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a9668c5fb6'
down_revision = '9a728cfbb15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'status')
    # ### end Alembic commands ###
