"""empty message

Revision ID: 5ec66224d791
Revises: 0ea01562739b
Create Date: 2020-09-21 14:38:00.851609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec66224d791'
down_revision = '0ea01562739b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'status')
    # ### end Alembic commands ###
