"""empty message

Revision ID: dc92d98cc319
Revises: 
Create Date: 2020-09-15 00:41:38.381875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc92d98cc319'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cover_letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letter_file_name'), 'cover_letter', ['file_name'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_file_name'), 'resume', ['file_name'], unique=False)
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('cl_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cl_id'], ['cover_letter.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_company'), 'listing', ['company'], unique=False)
    op.create_index(op.f('ix_listing_date_added'), 'listing', ['date_added'], unique=False)
    op.create_index(op.f('ix_listing_description'), 'listing', ['description'], unique=False)
    op.create_index(op.f('ix_listing_location'), 'listing', ['location'], unique=False)
    op.create_index(op.f('ix_listing_title'), 'listing', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_title'), table_name='listing')
    op.drop_index(op.f('ix_listing_location'), table_name='listing')
    op.drop_index(op.f('ix_listing_description'), table_name='listing')
    op.drop_index(op.f('ix_listing_date_added'), table_name='listing')
    op.drop_index(op.f('ix_listing_company'), table_name='listing')
    op.drop_table('listing')
    op.drop_index(op.f('ix_resume_file_name'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_cover_letter_file_name'), table_name='cover_letter')
    op.drop_table('cover_letter')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
